#!/usr/bin/env node
/**
 * Build script that injects the version from package.json into the source code.
 * This allows the package to remain isomorphic (browser-compatible) while
 * automatically keeping the version in sync with package.json.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const packageJsonPath = join(__dirname, '..', 'package.json')
const versionFilePath = join(__dirname, '..', 'src', 'version.ts')

const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'))
const version = packageJson.version

const versionFileContent = `// Auto-generated by scripts/inject-version.mjs - DO NOT EDIT
// This file is regenerated during the build process to keep the version in sync with package.json
export const VERSION = '${version}'
`

writeFileSync(versionFilePath, versionFileContent)
console.log(`Injected version ${version} into src/version.ts`)
