// Auto-generated by scripts/inject-version.mjs - DO NOT EDIT
// This file is regenerated during the build process to keep the version in sync with package.json
export const VERSION = '0.1.0-alpha.0'
